
NumPy 是 Python 科学计算的基石，它提供了高性能的多维数组对象（ndarray）以及用于操作这些数组的强大工具。掌握其常用函数，能让你在处理数据时更加高效、简洁。

以下是 NumPy 常用函数的分类介绍和解释。

## 🏗️ 数组创建函数
- 这些函数用于从现有数据或特定规则创建新的 NumPy 数组。

| 函数 | 作用 | 示例 |
| :--- | :--- | :--- |
| `np.array()` | 从 Python 列表或元组创建数组 | `np.array([1, 2, 3])` |
| `np.zeros()` | 创建指定形状的全 0 数组 | `np.zeros((2, 3))` (2行3列) |
| `np.ones()` | 创建指定形状的全 1 数组 | `np.ones((3, 2))` (3行2列) |
| `np.full()` | 创建指定形状和填充值的数组 | `np.full((2, 2), 5)` (2x2全为5) |
| `np.arange()` | 创建等间隔的整数数组（类似内置 `range`） | `np.arange(0, 10, 2)` → `[0, 2, 4, 6, 8]` |
| `np.linspace()` | 创建指定数量、等间隔的数组（支持浮点数） | `np.linspace(0, 1, 5)` → `[0., 0.25, 0.5, 0.75, 1.]` |
| `np.random.rand()` | 生成 `[0, 1)` 区间内均匀分布的随机数 | `np.random.rand(3, 2)` (3行2列) |
| `np.random.randn()` | 生成标准正态分布（均值为0）的随机数 | `np.random.randn(3, 3)` (3x3矩阵) |



### np.array()
- 作用： 从 Python 现有的数据结构（如列表 list、元组 tuple）转换创建数组。这是最基础的创建方式。
- 特点： 它可以接受嵌套序列（比如列表的列表）来创建多维数组。
- 常用参数： dtype（指定数据类型）。

In [ ]:
import numpy as np

# 从列表创建一维数组
a = np.array([1,2,3])
# 输出: [1 2 3]

# 从嵌套列表创建二维数组
b = np.array([[1,2],[3,4]])
# 输出: [[1 2]
#        [3 4]]

### np.zeros()
- 作用： 创建指定形状的数组，且所有元素初始化为 0。
- 应用场景： 当你需要构建一个占位符数组，或者在算法中需要累加数值时（初始值为0），非常有用。
- 参数： 第一个参数是形状（shape），可以是整数（一维）或元组（多维）。

In [ ]:
# 创建长度为 3 的一维全 0 数组
z1 = np.zeros(3)
# 输出: [0. 0. 0. ] (注意默认是浮点型 float)

# 创建 2x3 的全 0 矩阵
z2 = np.zeros((2,3))
# 输出: [[0. 0. 0.]
#        [0. 0. 0.]]

### np.ones()
- 作用： 创建指定形状的数组，且所有元素初始化为 1。
- 应用场景： 常用于初始化权重，或者作为乘法单位元进行计算。

In [ ]:
# 创建长度为 4 的全 1 数组
o = np.ones(4)
# 输出: [1. 1. 1. 1.]

### np.full()
- 作用： 创建指定形状和指定填充值的数组。
- 特点： <font color='red'>它是 zeros 和 ones 的通用版本</font>。如果你想填充的值不是 0 或 1，就用这个。
- 参数： 第一个参数是形状，第二个参数是填充值。

In [ ]:
# 创建 2x2 的数组，所有元素都是 7
f = np.full((2,2),7)
# 输出: [[7 7]
#        [7 7]]

### np.arange()
- 作用： 创建等间隔的整数数组。
- 特点： <font color='red'>它的用法非常像 Python 内置的 range() 函数，但返回的是 NumPy 数组而不是迭代器。</font>
- 参数： start (开始), stop (结束, 不包含), step (步长)。

In [ ]:
# 类似 range(5)，生成 0 到 4
a1 = np.arange(5)
# 输出: [0 1 2 3 4]

# 指定开始、结束和步长
a2 = np.arange(2,10,2)
# 输出: [2 4 6 8]

### np.linspace()
- 作用： 创建指定数量、等间隔的数组。
- 重要区别： <font color='red'>与 arange 指定“步长”不同，linspace 指定的是“样本数量”。它会自动计算步长。</font>
- 关键点： 默认情况下，结束值 stop 是包含在内的。
- 应用场景： 在绘图（如 Matplotlib）中生成 X 轴坐标时非常常用。

In [ ]:
# 在 0 到 10 之间，生成 5 个等间隔的数
l = np.linspace(0, 10, 5)
# 计算逻辑: 0, 2.5, 5.0, 7.5, 10.0
# 输出: [ 0.   2.5  5.   7.5 10. ]

### np.random.rand()
- 作用： 生成 [0, 1) 区间内均匀分布的随机数。
- 特点： 从 0（包含）到 1（不包含）之间随机取值，每个数出现的概率相等。
- 参数： 直接传入维度的大小（整数），而不是元组。

In [ ]:
# 生成 2x3 的随机矩阵
r = np.random.rand(2, 3)
# 输出示例: [[0.5488 0.7151 0.6027]
#           [0.5448 0.4236 0.6458]]

### np.random.randn()
- 作用： 生成标准正态分布（高斯分布）的随机数。
- 特点： 生成的数值均值为 0，方差为 1。数值主要集中在 0 附近，也有可能出现负数。
- 应用场景： 深度学习中初始化神经网络权重时常用。

In [ ]:
# 生成 4 个服从标准正态分布的随机数
n = np.random.randn(4)
# 输出示例: [ 0.4967 -0.1382  1.4052 -0.8877] (会有正有负)

| 函数类别 | 函数名 | 核心区别 |
| :--- | :--- | :--- |
| 基础转换 | `array` | 将 Python 列表转为数组 |
| 填充值 | `zeros`, `ones`, `full` | 分别填充 0, 1, 或任意指定数值 |
| 序列生成 | `arange`, `linspace` | `arange` 指定步长(左闭右开); `linspace` 指定数量(默认闭区间) |
| 随机生成 | `rand`, `randn` | `rand` 是 0-1 均匀分布; `randn` 是均值 0 的正态分布 |

## ✂️ 数组操作函数
- 这些函数用于改变数组的形状、结构或对其进行组合与分割。

| 函数 | 作用 | 示例 |
| :--- | :--- | :--- |
| `arr.reshape()` | 改变数组的形状，不改变数据 | `arr.reshape(3, 4)` |
| `arr.flatten()` | 将多维数组展平为一维数组 | `arr.flatten()` |
| `np.concatenate()` | 沿指定轴连接多个数组 | `np.concatenate((arr1, arr2), axis=0)` |
| `np.split()` | 将数组分割成多个子数组 | `np.split(arr, 3)` |
| `arr.T` 或 `np.transpose()` | 转置数组（行列互换） | `arr.T` |
| `np.hstack()` | 水平（按列）堆叠数组 | `np.hstack((arr1, arr2))` |
| `np.vstack()` | 垂直（按行）堆叠数组 | `np.vstack((arr1, arr2))` |
| `np.copy()` | 创建数组的完整副本（深拷贝） | `new_arr = np.copy(arr)` |



### arr.reshape()
- 作用： 改变数组的形状，但不改变数据。
- 详细解释： 这是最常用的变形函数。比如你有一个包含 12 个元素的一维数组，你可以把它变成 3行4列的二维数组。
- 注意： 变换前后的元素总数必须一致（例如 12 个元素可以变成 3x4，也可以变成 2x6，但不能变成 3x5）。

In [1]:
import numpy as np

arr = np.arange(12)  # [0, 1, ..., 11]
# 将一维数组变为 3行4列
new_arr = arr.reshape(3,4)
print(new_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### arr.flatten()
- 作用： 将多维数组展平为一维数组。
- 详细解释： 无论数组有多少层嵌套（比如 3x3x3 的立方体），这个函数都会把它“压扁”成一条直线。
- 注意： 它返回的是一个副本，修改新数组不会影响原数组。

In [2]:
arr = np.array([[1, 2], [3, 4]])
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4]


### np.concatenate()
- 作用： 沿指定轴连接多个数组。
- 详细解释： <font color='red'>这是最通用的拼接函数。你可以通过 axis 参数控制拼接的方向。</font>
- axis=0：默认值，沿着第一个轴（通常是行）拼接，即“上下”拼接。
- axis=1：沿着第二个轴（通常是列）拼接，即“左右”拼接。

In [ ]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

# 上下拼接 (变成2行2列)
np.concatenate((a, b), axis=0)
# 输出: [[1 2]
#        [3 4]]

### np.split()
- 作用： 将数组分割成多个子数组。
- 详细解释： 它是 concatenate 的逆操作。你可以指定分割的数量或者具体的分割位置。

In [ ]:
arr = np.arange(6) # [0 1 2 3 4 5]
# 将数组平均分成 3 份
sub_arrays = np.split(arr, 3)
# 输出: [array([0, 1]), array([2, 3]), array([4, 5])]

### arr.T 或 np.transpose()
- 作用： 转置数组（行列互换）。
- 详细解释： 对于二维数组，就是行变列，列变行。对于高维数组，它会反转轴的顺序。这在矩阵运算中非常常见。

In [ ]:
arr = np.array([[1, 2], [3, 4]])
# 转置
transposed = arr.T
# 输出: [[1 3]
#        [2 4]]

### np.hstack()
- 作用： <font color='red'>水平（按列）堆叠数组。</font>
- 详细解释： h 代表 horizontal。它专门用于将数组“左右”拼在一起。对于二维数组，这相当于 concatenate 的 axis=1。

In [ ]:
a = np.array([[1], [2]])
b = np.array([[3], [4]])
# 左右拼接
np.hstack((a, b))
# 输出: [[1 3]
#        [2 4]]

### np.vstack()
- 作用： <font color='red'>垂直（按行）堆叠数组。</font>
- 详细解释： v 代表 vertical。它专门用于将数组“上下”拼在一起。对于二维数组，这相当于 concatenate 的 axis=0

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
# 上下拼接
np.vstack((a, b))
# 输出: [[1 2]
#        [3 4]]

### np.copy()
- 作用： <font color='red'>创建数组的完整副本（深拷贝）。</font>
- 详细解释： <font color='red'>在 NumPy 中，简单的赋值（b = a）只是创建了一个引用（视图），修改 b 会导致 a 也被修改。使用 copy() 可以创建一个完全独立的新内存块，互不干扰。</font>

In [ ]:
arr = np.array([1, 2, 3])
# 创建深拷贝
new_arr = np.copy(arr)

new_arr[0] = 99
# arr 保持不变: [1 2 3]
# new_arr 变为: [99 2 3]

### 总结

这张表涵盖了 NumPy 数据处理的“骨架”操作：

- 变形： reshape, flatten, T
- 组合： concatenate, hstack, vstack
- 分割： split
- 安全复制： copy

## 🧮 数学与统计函数
- NumPy 的核心优势在于其向量化运算能力，这些函数可以直接对整个数组进行计算，无需编写循环。

| 函数 | 作用 | 示例 |
| :--- | :--- | :--- |
| `np.sum()` | 计算数组元素的总和 | `np.sum(arr)` |
| `np.mean()` | 计算数组元素的算术平均值 | `np.mean(arr)` |
| `np.max()` / `np.min()` | 计算数组元素的最大值 / 最小值 | `np.max(arr)` |
| `np.argmax()` / `np.argmin()` | 返回最大值 / 最小值的索引位置 | `np.argmax(arr)` |
| `np.std()` / `np.var()` | 计算标准差 / 方差 | `np.std(arr)` |
| `np.add()` / `np.subtract()` | 数组加法 / 减法（也支持 `+` / `-` 运算符） | `np.add(arr1, arr2)` |
| `np.multiply()` / `np.divide()` | 数组乘法 / 除法（也支持 `*` / `/` 运算符） | `np.multiply(arr1, arr2)` |
| `np.dot()` | 计算两个数组的点积（矩阵乘法） | `np.dot(arr1, arr2)` |
| `np.exp()` | 计算 e 的幂（e^x） | `np.exp(arr)` |
| `np.sqrt()` | 计算平方根 | `np.sqrt(arr)` |
| `np.sin()` / `np.cos()` | 计算三角函数（正弦 / 余弦） | `np.sin(arr)` |



### np.sum()
- 作用： 计算数组所有元素的总和。
- 场景： 计算总销售额、总像素值等。

In [ ]:
arr = np.array([1, 2, 3])
print(np.sum(arr))

### np.mean()
- 作用： 计算数组元素的算术平均值。
- 场景： 计算平均分、平均气温等。

In [ ]:
arr = np.array([1, 2, 3])
print(np.mean(arr)) # 输出: 2.0

### np.max() / np.min()
- 作用： 分别计算数组中的最大值和最小值。
- 场景： 寻找数据中的极值点。

In [ ]:
arr = np.array([1, 5, 3])
print(np.max(arr))  # 输出: 5
print(np.min(arr))  # 输出: 1

### np.argmax() / np.argmin()
- 作用： 返回最大值或最小值所在的索引位置，而不是值本身。
- 场景： <font color='red'>在分类任务中找到概率最大的类别索引</font>

In [ ]:
arr = np.array([10, 50, 30])
print(np.argmax(arr)) # 输出: 1 (因为50最大，它的索引是1)

### np.std() / np.var()
- 作用： 分别计算标准差和方差。
- 场景： 衡量数据的波动程度（离散程度）。方差越大，数据越分散。

In [ ]:
arr = np.array([1, 2, 3])
print(np.var(arr))  # 方差
print(np.std(arr))  # 标准差

### np.dot()
- 作用： 计算两个数组的点积。
- 重要区别： 对于一维数组，它是内积（对应元素相乘再求和）；对于二维数组，它是矩阵乘法。这与上面的 multiply 完全不同。

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b)) 
# 执行矩阵乘法运算

[[19 22]
 [43 50]]


### np.exp()
作用： 计算 $e^x$（自然指数函数），其中 e 约为 2.718。
场景： 机器学习中常用的 Sigmoid 函数或 Softmax 函数都会用到它。


In [ ]:
arr = np.array([0, 1])
print(np.exp(arr)) # 输出: [1.         2.71828183]

### np.sqrt()
- 作用： 计算每个元素的平方根。
- 场景： 计算欧氏距离等。

In [ ]:
arr = np.array([4, 9, 16])
print(np.sqrt(arr)) # 输出: [2. 3. 4.]

### np.sin() / np.cos()
- 作用： 计算三角函数（正弦、余弦）。
- 注意： 输入通常是弧度。

In [ ]:
# 计算 π/2 的正弦值 (应为 1)
print(np.sin(np.pi / 2)) # 输出: 1.0

## 💡 关键概念：<font color='red'>axis 参数</font>

在处理多维数组时，许多统计函数（如 sum, mean, max）都支持 axis 参数，它指定了计算所沿着的轴。

- axis=0: 沿着行的方向计算（即“跨行”），结果是按列聚合。
- axis=1: 沿着列的方向计算（即“跨列”），结果是按行聚合。

In [ ]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# 计算所有元素的总和
print(np.sum(matrix))        # 输出: 21

# 按列求和 (axis=0)，结果为每列的和
print(np.sum(matrix, axis=0)) # 输出: [5 7 9]

# 按行求和 (axis=1)，结果为每行的和
print(np.sum(matrix, axis=1)) # 输出: [6 15]

## 🔍 索引与筛选

- 除了使用常规的方括号 [] 进行索引和切片，NumPy 还提供了更强大的筛选方式。
### 布尔索引 (Boolean Indexing)
通过条件表达式生成一个布尔数组（True/False），然后用它来筛选出符合条件的元素。

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
# 筛选出所有大于 3 的元素
print(arr[arr > 3])  # 输出: [4 5 6]

# 筛选出所有偶数
print(arr[arr % 2 == 0]) # 输出: [2 4 6]

### 花式索引 (Fancy Indexing)
使用整数数组或列表作为索引，来获取不连续的元素。

In [ ]:
arr = np.array([10, 11, 12, 13, 14])
# 获取索引为 0, 2, 4 的元素
print(arr[[0, 2, 4]])  # 输出: [10 12 14]