### 作用：保留矩阵的下三角部分（包括对角线），上三角部分置为0。

In [ ]:
torch.tril(input, diagonal=0)

| 参数         | 说明                        |
| ---------- | ------------------------- |
| `input`    | 输入张量                      |
| `diagonal` | 对角线索引（0=主对角线，>0=上移，<0=下移） |


In [ ]:
原始矩阵:              torch.tril (diagonal=0):
[1  2  3  4]           [1  0  0  0]
[5  6  7  8]    →      [5  6  0  0]
[9  10 11 12]          [9  10 11 0]
[13 14 15 16]          [13 14 15 16]
 ↑                      ↑
 上三角被置为0          保留对角线及以下

In [2]:
import torch

# 创建4*4矩阵
x = torch.arange(1,17).view(4,4)
print("原始矩阵：")
print(x)

print("\n" + "="*30)

# diagonal=0 保留主对角线及以下（默认)
print(torch.tril(x))

原始矩阵：
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

tensor([[ 1,  0,  0,  0],
        [ 5,  6,  0,  0],
        [ 9, 10, 11,  0],
        [13, 14, 15, 16]])


In [ ]:
# diagonal=-1 保留下对脚下及以下（下移1位，不含主对角线）
print(torch.tril(x,diagonal=-1))