# PyTorch 张量的广播机制是什么意思？

广播是一种强大的机制，<font color='red'>它允许不同形状的张量进行算术运算，而无需显式地复制数据（节省内存）。</font>

### 广播规则

当两个张量形状不同时，PyTorch 会从尾部维度（最右边）开始向前检查，只要满足以下任一条件，就可以广播：
1. 维度大小相等。
2. 其中一个维度大小为 1。
3. 其中一个张量缺少该维度。

### 直观例子
想象一个矩阵（大）和一个向量（小）相加。

In [5]:
import torch
# 矩阵A ：3行 4列
A = torch.ones(3,4)
print(A)

# 向量B：4个元素（形状为[4]
B = torch.arange(4)
print(B)

# 运算
C = A + B

print(C)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([0, 1, 2, 3])
tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])


### 发生了什么？

虽然 A 是 (3, 4)，B 是 (4,)，形状不同，但 PyTorch 会“广播” B：

- <font color='red'>它会在逻辑上把 B 复制 3 份，使其变成 (3, 4) 的形状。</font>
- 然后与 A 逐元素相加。
- 关键点：实际上并没有真的复制数据（为了省内存），只是在计算时做了逻辑上的扩展。

### 典型应用场景
- 归一化：从一批图片数据中减去均值（均值通常是一个小向量）。
- 加偏置：在全连接层中，矩阵乘法结果加上偏置向量。