torch.Tensor.repeat() 方法用于沿着指定的维度重复张量。
- 这个方法非常有用，尤其是在需要扩展张量大小以匹配其他张量的形状时。
以下是对 torch.Tensor.repeat() 方法的详细解释和示例。

In [1]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print("Original shape:", x.shape)  # 输出: torch.Size([2, 3])

Original shape: torch.Size([2, 3])


In [4]:
# 在每个维度上重复张量
x_repeated = x.repeat(2, 2)
print("Shape after repeat:", x_repeated.shape)  # 输出: torch.Size([4, 6])
print(x_repeated)
      
# 这会在第0维重复2次，在第1维重复2次，生成一个新的形状为 (4, 6) 的张量：

Shape after repeat: torch.Size([4, 6])
tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6],
        [1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])


In [5]:
# 在特定维度上重复张量
x_repeated_0 = x.repeat(3, 1)
print("Shape after repeat at dim 0:", x_repeated_0.shape)  # 输出: torch.Size([6, 3])
print(x_repeated_0)

Shape after repeat at dim 0: torch.Size([6, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])


In [6]:
# 这会在第1维重复4次，生成一个新的形状为 (2, 12) 的张量：
x_repeated_1 = x.repeat(1, 4)
print("Shape after repeat at dim 1:", x_repeated_1.shape)  # 输出: torch.Size([2, 12])
print(x_repeated_1)

Shape after repeat at dim 1: torch.Size([2, 12])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])
