unsqueeze(1) 再 squeeze(1) 的“先加维再降维”

In [3]:
import torch

# 原始张量
x = torch.tensor([10,20,30])
print(x)
print(x.shape)

# 

tensor([10, 20, 30])
torch.Size([3])


# unsqueeze(1) 扩展一个长度为1的维度

In [2]:

# 将一维向量x，变为列向量
y = x.unsqueeze(1)
print(y.shape)
print(y)

torch.Size([3, 1])
tensor([[10],
        [20],
        [30]])


In [8]:
# gather 之后

# 假设我们要按”列号’取值，索引也必须是[3,1]
idx = torch.tensor([[0],[0],[0]])
print(ids.shape)

out = y.gather(dim=1,index=idx)
print(out)

torch.Size([3, 1])
tensor([[10],
        [20],
        [30]])


# squeeze(1) 挤掉长度为1的维度

In [10]:
final = out.squeeze(1)
print(final.shape)
print(final)


torch.Size([3])
tensor([10, 20, 30])
