# 创建tensor

In [3]:
import torch

In [4]:
torch.tensor([1,2]) , torch.tensor([[1,2],[3,4]])

(tensor([1, 2]),
 tensor([[1, 2],
         [3, 4]]))

In [5]:
import numpy as np

# 从numpy创建
torch.from_numpy(np.array([1,2]))

tensor([1, 2])

In [10]:
print(torch.ones((2,3)))

print(torch.zeros((2,3)))

print(torch.full([2,3],8))

print(torch.eye(3,4))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[8, 8, 8],
        [8, 8, 8]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


In [11]:
# 创建但不初始化
print(torch.empty(2,3))

tensor([[8.4078e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [12]:
# 标准的正太分布
print(torch.randn(2,3))

tensor([[-0.4437,  0.3377, -0.8883],
        [-0.8123,  1.3992, -0.5475]])


In [13]:
# 0-1均匀分布
print(torch.rand(2,3))

tensor([[0.1694, 0.3078, 0.2288],
        [0.1338, 0.6535, 0.3645]])


In [14]:
# 1-9的整数均匀分布
print(torch.randint(1,10,[2,3]))

tensor([[8, 4, 2],
        [2, 7, 1]])


In [16]:
# 自增数列，0到9，步长为1
print(torch.arange(0,10,2))

tensor([0, 2, 4, 6, 8])


In [17]:
# 等差数列 0-10,4个数
print(torch.linspace(0,10,4))

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


In [19]:
# 指定类型的创建
torch.FloatTensor([1,2]), torch.LongTensor([1,2])

(tensor([1., 2.]), tensor([1, 2]))

In [20]:
# 获取数据的类型
torch.randn(2,3).dtype

torch.float32

In [21]:
# 转换数据类型
torch.randn(2,3).to(torch.float64).dtype

torch.float64

# 索引tensor

In [22]:
import torch


In [29]:
# 创建测试数据
# 4张图片，3通道，28*28像素
a = torch.randn(4,3,28,28)
a.shape,a.dtype


(torch.Size([4, 3, 28, 28]), torch.float32)

## 直接索引

In [30]:


# 查看第0张图片
print(a[0].shape)

torch.Size([3, 28, 28])


In [32]:
# 查看第0张图片的第0个通道
print(a[0,0].shape)

torch.Size([28, 28])


In [35]:
# 查看第0张图片的第0个通道的第2行
print([a[0,0,2]])

[tensor([ 0.1978, -0.2106, -0.6783, -1.2441, -0.2153,  0.6405, -0.8345, -1.5391,
        -1.6522,  0.5904,  1.5483, -2.5016,  0.2411,  0.3048,  2.1532,  0.3051,
         0.6112, -0.8581,  0.6744, -1.9803, -1.4811, -1.0528, -0.5938,  0.8452,
         0.0527,  0.6357, -0.2621, -1.3046])]


In [34]:
# 查看第0张图片的第0个通道的第2列的第四行
print(a[0,0,2,4])

tensor(-0.2153)


## 切片



In [36]:
# 查看第0,1张图片
print(a[:2].shape)

torch.Size([2, 3, 28, 28])


In [39]:
# 查看第0,1张图片的0,1通道
print(a[0:2,0:2].shape)
print(a[:2,:2].shape)

torch.Size([2, 2, 28, 28])
torch.Size([2, 2, 28, 28])


In [42]:
# 查看0,1张图片的所有通道的倒数5至正数24行
print(a[:2,:,-5:25].shape)

torch.Size([2, 3, 2, 28])


In [44]:
# 有间隔的索引
print(a[:,:,:,::2].shape)

torch.Size([4, 3, 28, 14])


## 用...表示多个被省略的

In [46]:
# 取所有图片的第0-2列
print(a[...,:2].shape)

torch.Size([4, 3, 28, 2])


In [47]:
# 取所有图片的第0-2行
print(a[...,:2,:].shape)

torch.Size([4, 3, 2, 28])


In [48]:
# 取第2张图片
print(a[2,...].shape)

torch.Size([3, 28, 28])


# tensor维度变换

##  view 和reshape维度变换
- view： 要求张量是连续的（contiguous）。如果张量不是连续的（例如，经过某些操作如 transpose 后），view 会报错。
  - 数据的总元素数量必须保持不变。
  
- reshape： 不要求张量是连续的。即使张量不是连续的，reshape 也可以正常工作。
  - 数据的总元素数量必须保持不变。


In [49]:
# 4张图片，一个通道，28*28像素
a = torch.randn(4,1,28,28)
print(a.shape)

torch.Size([4, 1, 28, 28])


In [50]:
# 转换为4,784维度，相当于打平
print(a.reshape(4,784).shape)

torch.Size([4, 784])


In [51]:
# 再转换为4,28,28维度
print((a.reshape(4,784)).reshape(4,28,28).shape)

torch.Size([4, 28, 28])


In [52]:
# view的用法和reshape的用法完全一样
print(a.view(4,784).shape)

torch.Size([4, 784])


In [55]:
# 检查张量是否是连续的
x = torch.randn(2,3)
print(x.is_contiguous())

True


## unsqueeze插入维度


In [56]:
# 2*2的tensor
a = torch.randn(2,3)
print(a.shape)

torch.Size([2, 3])


In [57]:
# 在第0维插入一个维度
print(a.unsqueeze(0).shape)

torch.Size([1, 2, 3])


In [58]:
# 在倒数第一维插入维度
print(a.unsqueeze(-1).shape)

torch.Size([2, 3, 1])


## squeeze删除维度，只能删除为1的维度


In [60]:
a = torch.randn(1,2,3,1)
print(a.shape)

torch.Size([1, 2, 3, 1])


In [61]:
# 删除第0维
print(a.squeeze(0).shape)

torch.Size([2, 3, 1])


In [62]:
# 删除最后一维
print(a.squeeze(-1).shape)

torch.Size([1, 2, 3])


In [63]:
# 删除所有为1的维度
print(a.squeeze().shape)

torch.Size([2, 3])


## repeat复制维度


In [64]:
# 分别复制2次和3次
print(torch.randn(2,3).repeat(2,3).shape)

torch.Size([4, 9])


## 维度交换


In [65]:
# t转置，只能操作2维tensor
print(torch.randn(1,2).t().shape)

torch.Size([2, 1])


In [66]:
# ranspose维度交换，指定要转换的维度，只能两两交换
print(torch.randn(1,2,3).transpose(0,1).shape)

torch.Size([2, 1, 3])


In [67]:
# permute维度交换，输入维度的顺序
print(torch.randn(1,2,3).permute(2,1,0).shape)

torch.Size([3, 2, 1])


# broadcat 广播

In [70]:
# broadcast

a = torch.randn(2,3)
b = torch.randn(1,3)
c = torch.randn(1)

print((a+b).shape)
print((a+c).shape)


torch.Size([2, 3])
torch.Size([2, 3])


In [73]:
# 手动broadcast
print(b.expand_as(a).shape)
print(b.expand_as(a))

print(c.expand_as(a).shape)

torch.Size([2, 3])
tensor([[ 0.6000,  0.0973, -0.2941],
        [ 0.6000,  0.0973, -0.2941]])
torch.Size([2, 3])


# tensor的拼接和拆分
- torch.cat
- torch.stack
- torch.split
- torch.chunk

In [74]:
a = torch.rand(4,32,8)
b = torch.rand(5,32,8)

In [76]:
# cat拼接,dim=0是指定要拼接的维度
torch.cat([a,b],dim=0).shape

torch.Size([9, 32, 8])

In [78]:
# stack组合，会创建一个新的维度，用来区分组合后的两个tensor

a = torch.rand(5,32,8)
b = torch.rand(5,32,8)
# a和b 的size必须是相同
torch.stack([a,b],dim=0).shape

torch.Size([2, 5, 32, 8])

In [79]:
a = torch.rand(4,32,8)

# split拆分，在0维度上拆分，每2个元素1拆分
_1,_2 = a.split(2,dim=0)
print(_1.shape)
print(_2.shape)

torch.Size([2, 32, 8])
torch.Size([2, 32, 8])


In [81]:
_1,_2,_3 = a.split([1,2,1],dim=0)
print(_1.shape)
print(_2.shape)
print(_3.shape)

torch.Size([1, 32, 8])
torch.Size([2, 32, 8])
torch.Size([1, 32, 8])


In [84]:
a = torch.rand(7,32,8)

# chunk拆分，在0维度上拆分，拆成2个
_1,_2 = a.chunk(2,dim=0)
print(_1.shape)
print(_2.shape)

torch.Size([4, 32, 8])
torch.Size([3, 32, 8])


# 数学运算

In [4]:
#测试数据
a = torch.FloatTensor([[0, 1, 2], [3, 4, 5]])
b = torch.FloatTensor([0, 1, 2])

a, b

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [86]:
#四则运算
print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([[0., 2., 4.],
        [3., 5., 7.]])
tensor([[0., 0., 0.],
        [3., 3., 3.]])
tensor([[ 0.,  1.,  4.],
        [ 0.,  4., 10.]])
tensor([[   nan, 1.0000, 1.0000],
        [   inf, 4.0000, 2.5000]])


In [87]:
#矩阵乘法
print(a @ b)
print(a.matmul(b))

#计算过程
0 * 0 + 1 * 1 + 2 * 2, 0 * 3 + 1 * 4 + 2 * 5

tensor([ 5., 14.])
tensor([ 5., 14.])


(5, 14)

In [88]:
# 指数、对数运算

# 求指数
print(a**2)

# 开根号
print(a**0.5)

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])


In [89]:
# 求e的n次方
print(a.exp())

tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5982, 148.4132]])


In [90]:
# 以e为底，求对数
print(a.log())

tensor([[  -inf, 0.0000, 0.6931],
        [1.0986, 1.3863, 1.6094]])


In [91]:
# 以2为底，求对数
print(a.log2())

tensor([[  -inf, 0.0000, 1.0000],
        [1.5850, 2.0000, 2.3219]])


In [92]:
# 裁剪，限制数据的上下限制
a.clamp(2,4)

tensor([[2., 2., 2.],
        [3., 4., 4.]])

In [93]:
#逻辑运算

#大于
print(a > b)

#小于
print(a < b)

#等于
print(a == b)

#不等于
print(a != b)

tensor([[False, False, False],
        [ True,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[ True,  True,  True],
        [False, False, False]])
tensor([[False, False, False],
        [ True,  True,  True]])


In [94]:
#四舍五入
c = torch.FloatTensor([3.14])

#向下取整
print(c.floor())

#向上取整
print(c.ceil())

#四舍五入
print(c.round())

tensor([3.])
tensor([4.])
tensor([3.])


# 属性统计

In [95]:
#测试数据
a = torch.FloatTensor([[0., 1., 2.], [3., 4., 5.]])

a

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [96]:
#求最小
print(a.min())

#求最大
print(a.max())

#求平均
print(a.mean())

#求积
print(a.prod())

#求和
print(a.sum())

#求最大值下标
print(a.argmax())

#求最小值下标
print(a.argmin())

tensor(0.)
tensor(5.)
tensor(2.5000)
tensor(0.)
tensor(15.)
tensor(5)
tensor(0)


In [97]:
#分维度求最大
a.max(dim=0)

torch.return_types.max(
values=tensor([3., 4., 5.]),
indices=tensor([1, 1, 1]))

In [6]:
a

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [5]:
#分维度求最大值下标
a.argmax(dim=0)

tensor([1, 1, 1])

In [7]:
#分维度求最大值下标
a.argmax(dim=1)

tensor([2, 2])

In [8]:
#求1范数
print(a.norm(1))
print(a.norm(1, dim=0))

#求2范数
print(a.norm(2))
print(a.norm(2, dim=0))

tensor(15.)
tensor([3., 5., 7.])
tensor(7.4162)
tensor([3.0000, 4.1231, 5.3852])


In [9]:
#求前2个最小值
a.topk(2, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[0., 1.],
        [3., 4.]]),
indices=tensor([[0, 1],
        [0, 1]]))

In [10]:
#求第2个小的值
a.kthvalue(2, dim=1)

torch.return_types.kthvalue(
values=tensor([1., 4.]),
indices=tensor([1, 1]))