# 优化和调参

## torch.optim.lr_scheduler 学习率调度器，用于调整学习率
- 它提供了多种策略来在训练过程中改变优化器的学习率，帮助模型更好地收敛。

In [ ]:
import torch
import torch.nn as nn
from torch.optim import SGD
from torch.optim.lr_scheduler import StepLR, CosineAnnealingLR, ReduceLROnPlateau

# 标准使用流程
model = nn.Linear(10, 2)
optimizer = SGD(model.parameters(), lr=0.1)
scheduler = StepLR(optimizer, step_size=10, gamma=0.1)  # 每10个epoch，lr *= 0.1

for epoch in range(100):
    # 训练...
    train(...)
    
    # 验证...
    validate(...)
    
    scheduler.step()  # 更新学习率（关键！）

## 基于epoch的衰减（无需验证指标）

| 调度器                 | 策略                                 | 适用场景        |
| ------------------- | ---------------------------------- | ----------- |
| `StepLR`            | 每隔 step\_size 个 epoch，lr \*= gamma | 常规训练        |
| `MultiStepLR`       | 在指定 milestones 处衰减                 | 分阶段训练       |
| `ExponentialLR`     | 每个 epoch，lr \*= gamma              | 平滑衰减        |
| `CosineAnnealingLR` | 余弦退火周期调整                           | 现代CNN/ViT训练 |


In [ ]:
# StepLR: 每30个epoch，学习率乘以0.1
scheduler = StepLR(optimizer, step_size=30, gamma=0.1)

# MultiStepLR: 在第30、60、80个epoch衰减
scheduler = MultiStepLR(optimizer, milestones=[30, 60, 80], gamma=0.1)

# CosineAnnealingLR: T_max为半周期长度，eta_min为最小lr
scheduler = CosineAnnealingLR(optimizer, T_max=100, eta_min=1e-6)

## 基于验证指标的衰减（需要监控性能）
| 调度器                           | 策略        | 特点      |
| ----------------------------- | --------- | ------- |
| `ReduceLROnPlateau`           | 验证指标停滞时衰减 | 最灵活，最常用 |
| `CosineAnnealingWarmRestarts` | 带热重启的余弦退火 | 逃离局部最优  |


In [ ]:
# 当验证loss 5个epoch不下降，lr *= 0.5
scheduler = ReduceLROnPlateau(
    optimizer, 
    mode='min',      # 'min' 监控loss, 'max' 监控acc
    factor=0.5,      # 衰减系数
    patience=5,      # 容忍epoch数
    verbose=True     # 打印学习率变化
)

# 训练循环中需要传入验证指标
val_loss = validate(...)
scheduler.step(val_loss)  # 注意：传入监控值！

## 高级策略： 预热 + 余弦退火（transformer标配）

In [ ]:
from torch.optim.lr_scheduler import LambdaLR, CosineAnnealingLR
import math

def get_cosine_schedule_with_warmup(optimizer, num_warmup_steps, num_training_steps):
    """带线性预热的余弦退火调度器（Hugging Face风格）"""
    def lr_lambda(current_step):
        if current_step < num_warmup_steps:
            return float(current_step) / float(max(1, num_warmup_steps))
        progress = float(current_step - num_warmup_steps) / float(max(1, num_training_steps - num_warmup_steps))
        return max(0.0, 0.5 * (1.0 + math.cos(math.pi * progress)))
    
    return LambdaLR(optimizer, lr_lambda)

# 使用
scheduler = get_cosine_schedule_with_warmup(
    optimizer, 
    num_warmup_steps=500, 
    num_training_steps=10000
)

## OneCycleLR（超收敛策略）

In [ ]:
# 先上升到max_lr，再下降到base_lr以下
scheduler = torch.optim.lr_scheduler.OneCycleLR(
    optimizer,
    max_lr=0.1,
    total_steps=1000,  # 或 epochs * steps_per_epoch
    pct_start=0.3,     # 上升阶段占比
    anneal_strategy='cos',  # 'cos' 或 'linear'
    div_factor=25.,    # 初始lr = max_lr/25
    final_div_factor=1e4   # 最终lr = 初始lr/1e4
)

In [ ]:
model = MyModel()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=0.01)

# 组合策略：预热 + 余弦退火
scheduler = get_cosine_schedule_with_warmup(
    optimizer, 
    num_warmup_steps=1000,
    num_training_steps=total_steps
)

for epoch in range(epochs):
    model.train()
    for batch in train_loader:
        # 前向/反向/优化
        loss = ...
        loss.backward()
        optimizer.step()
        scheduler.step()  # 每个step更新（OneCycleLR需要）
        optimizer.zero_grad()
    
    # 验证
    val_metric = evaluate(model, val_loader)
    
    # 可选：基于指标的调度
    # plateau_scheduler.step(val_metric)

## 注意事项

| 要点        | 说明                                                  |
| --------- | --------------------------------------------------- |
| **调用位置**  | `scheduler.step()` 放在 epoch 结束或 batch 结束（取决于策略）     |
| **顺序**    | `optimizer.step()` → `scheduler.step()`（新版本PyTorch） |
| **状态保存**  | 保存 `scheduler.state_dict()` 以恢复训练                   |
| **学习率读取** | `optimizer.param_groups[0]['lr']`                   |


In [ ]:
# 保存完整状态
checkpoint = {
    'model': model.state_dict(),
    'optimizer': optimizer.state_dict(),
    'scheduler': scheduler.state_dict(),  # 别忘了！
    'epoch': epoch
}
torch.save(checkpoint, 'checkpoint.pth')

# torch.optim.RMSprop: 它是 AdaGrad 的改进版，通过引入移动平均来解决学习率单调递减的问题，非常适合处理非平稳目标和递归神经网络（RNN）
- RMSprop 的核心思想是：为每个参数自适应地调整学习率，基于该参数历史梯度的平方的移动平均。

# 特殊用途函数和实用工具

## torch.distributed 支持分布式训练的模块
- torch.distributed 是 PyTorch 提供的分布式计算后端，支持多种通信后端（NCCL、Gloo、MPI），用于多 GPU、多节点的并行训练。


In [ ]:
import torch.distributed as dist

# 初始化进程组
dist.init_process_group(
    backend='nccl',      # 通信后端: nccl(推荐GPU)/gloo/cpu
    init_method='env://', # 初始化方式: env://(环境变量)/tcp://(指定地址)/file://
    world_size=4,        # 总进程数
    rank=0               # 当前进程ID (0 ~ world_size-1)
)

# 销毁进程组
dist.destroy_process_group()


### 常用后端对比

| 后端       | 适用场景       | 特点          |
| -------- | ---------- | ----------- |
| **NCCL** | NVIDIA GPU | 最优性能，支持多机多卡 |
| **Gloo** | CPU / GPU  | 通用性强，支持各种设备 |
| **MPI**  | 高性能集群      | 需要预装MPI库    |


### 核心通信原语

In [ ]:
import torch
import torch.distributed as dist

# 假设已初始化，world_size=4
tensor = torch.tensor([1.0]).cuda()

# 1. 广播 (Broadcast) - 从rank0广播到所有rank
dist.broadcast(tensor, src=0)

# 2. 规约 (Reduce) - 求和后存到rank0
dist.reduce(tensor, dst=0, op=dist.ReduceOp.SUM)

# 3. 全规约 (All-Reduce) - 求和后分发到所有rank ⭐最常用
dist.all_reduce(tensor, op=dist.ReduceOp.SUM)

# 4. 全收集 (All-Gather) - 收集所有rank的数据
tensor_list = [torch.zeros(1).cuda() for _ in range(4)]
dist.all_gather(tensor_list, tensor)

# 5. 散射 (Scatter) - 从rank0分发数据
dist.scatter(tensor, scatter_list=None, src=0)

# 6. 点对点发送/接收
if dist.get_rank() == 0:
    dist.send(tensor, dst=1)
else:
    dist.recv(tensor, src=0)

### 实际应用：DDP (DistributedDataParallel)

In [ ]:
import torch
import torch.nn as nn
from torch.nn.parallel import DistributedDataParallel as DDP

# 初始化
torch.cuda.set_device(local_rank)
dist.init_process_group(backend='nccl')

# 包装模型
model = MyModel().to(local_rank)
ddp_model = DDP(
    model,
    device_ids=[local_rank],
    output_device=local_rank,
    find_unused_parameters=False  # 动态图需设为True
)

# 训练（与普通模型用法相同）
output = ddp_model(input)
loss = criterion(output, target)
loss.backward()  # 梯度自动同步
optimizer.step()

### 启动： 单节点+ 多GPU

In [ ]:
# 使用 torchrun (推荐)
torchrun --nproc_per_node=4 train.py

# 或使用 python -m torch.distributed.launch (旧版)
python -m torch.distributed.launch --nproc_per_node=4 train.py

### 启动： 多节点+ 多GPU

In [ ]:
# Node 0 (主节点)
torchrun \
    --nnodes=2 \
    --node_rank=0 \
    --nproc_per_node=8 \
    --master_addr="192.168.1.1" \
    --master_port=12345 \
    train.py

# Node 1
torchrun \
    --nnodes=2 \
    --node_rank=1 \
    --nproc_per_node=8 \
    --master_addr="192.168.1.1" \
    --master_port=12345 \
    train.py

### 关键工具函数

In [ ]:
# 获取当前环境信息
dist.get_rank()       # 当前进程ID
dist.get_world_size() # 总进程数
dist.is_initialized() # 是否已初始化

# 同步屏障（所有进程到达后才继续）
dist.barrier()

# 检查后端支持
dist.is_nccl_available()
dist.is_gloo_available()
dist.is_mpi_available()

| 特性                               | 说明                                  |
| -------------------------------- | ----------------------------------- |
| **torch.distributed.fsdp**       | Fully Sharded Data Parallel，大模型分片训练 |
| **torch.distributed.rpc**        | 远程过程调用，支持参数服务器架构                    |
| **torch.distributed.elastic**    | 弹性训练，支持动态扩缩容                        |
| **torch.distributed.checkpoint** | 分布式模型检查点保存/加载                       |


### 使用流程
1. 设置环境变量 (RANK, WORLD_SIZE, MASTER_ADDR等)
   ↓
2. dist.init_process_group() 初始化
   ↓
3. 使用 DDP 包装模型 或 手动调用通信原语
   ↓
4. 训练循环
   ↓
5. dist.destroy_process_group() 清理

## torch.no_grad() 是一个禁用梯度计算的上下文管理器，主要用于推理阶段或不需要反向传播的操作。

### 核心机制

| 特性              | 说明                             |
| --------------- | ------------------------------ |
| **禁用 Autograd** | 不创建计算图，不跟踪操作历史                 |
| **节省内存**        | 不保存中间激活值，显存占用大幅降低              |
| **加速计算**        | 跳过梯度相关计算，速度更快                  |
| **不影响参数**       | 参数仍可修改（如通过 `optimizer.step()`） |


### 上下文管理器（推荐）

In [ ]:
import torch

model = torch.nn.Linear(10, 5)
input = torch.randn(2, 10)

with torch.no_grad():
    output = model(input)  # 不计算梯度
    # 内部所有操作都不追踪梯度

### 与 requires_grad 的区别

In [ ]:
import torch

# 场景1: 创建不追踪梯度的张量
x = torch.tensor([1.0], requires_grad=False)  # 永久不追踪

# 场景2: 临时禁用梯度（推荐用于推理）
x = torch.tensor([1.0], requires_grad=True)
with torch.no_grad():
    y = x * 2  # 不追踪
z = x * 3      # 追踪（退出上下文后恢复）

| 方式                    | 作用域      | 用途        |
| --------------------- | -------- | --------- |
| `requires_grad=False` | 张量级别，永久  | 冻结参数、输入数据 |
| `torch.no_grad()`     | 代码块级别，临时 | 推理、验证、测试  |


### 实际应用场景
- 场景1: 模型推理/评估

In [ ]:
model.eval()  # 设置评估模式（影响 BatchNorm/Dropout）
with torch.no_grad():  # 禁用梯度
    for data, target in test_loader:
        output = model(data)
        loss = criterion(output, target)
        # 不调用 loss.backward()，不更新参数

- 场景2: 计算指标（不训练）

In [ ]:
with torch.no_grad():
    accuracy = (pred.argmax(dim=1) == target).float().mean()
    # 纯计算，不需要梯度

- 场景3: 冻结部分网络

In [ ]:
# 方式1: 直接设置 requires_grad
for param in model.backbone.parameters():
    param.requires_grad = False

# 方式2: 使用 no_grad 上下文（仅推理时）
with torch.no_grad():
    features = model.backbone(input)  # 不计算 backbone 的梯度
output = model.head(features)         # head 部分计算梯度
loss.backward()  # 只更新 head 的参数

### torch.no_grad() vs torch.set_grad_enabled()

In [ ]:
# 方式1: 上下文管理器（推荐）
with torch.no_grad():
    ...

# 方式2: 全局开关（影响整个程序）
torch.set_grad_enabled(False)  # 全局禁用
# ... 推理代码 ...
torch.set_grad_enabled(True)   # 恢复

# 方式3: 条件控制
is_train = False
with torch.set_grad_enabled(is_train):
    output = model(input)

### 与 detach() 的关系

In [ ]:
x = torch.tensor([1.0], requires_grad=True)

# 方式1: no_grad 上下文
with torch.no_grad():
    y = x * 2  # y 无 grad_fn，但 x 的 requires_grad 不变

# 方式2: detach()
y = (x * 2).detach()  # 返回新张量，与原计算图分离

# 关键区别
with torch.no_grad():
    y = x * 2
# y.requires_grad = False, 但 x 仍追踪梯度

z = x.detach()
# z 是 x 的视图，共享内存，但 z.requires_grad = False

| 特性   | `no_grad()` | `detach()`  |
| ---- | ----------- | ----------- |
| 作用范围 | 代码块内所有操作    | 单个张量        |
| 内存   | 不共享         | 共享数据内存      |
| 使用场景 | 推理、评估       | 需要张量值但阻断梯度流 |


### 性能对比示例

In [3]:
import torch
import time

model = torch.nn.Linear(1000, 1000).cuda()
x = torch.randn(64, 1000).cuda()

# 有梯度
torch.cuda.synchronize()
start = time.time()
for _ in range(1000):
    out = model(x)
    loss = out.sum()
    loss.backward()
torch.cuda.synchronize()
print(f"With grad: {time.time() - start:.3f}s")  # 慢，内存占用高

# 无梯度
model.zero_grad()
torch.cuda.synchronize()
start = time.time()
with torch.no_grad():
    for _ in range(1000):
        out = model(x)
torch.cuda.synchronize()
print(f"No grad: {time.time() - start:.3f}s")    # 快，内存占用低

AssertionError: Torch not compiled with CUDA enabled

✅ 评估/测试时必须使用: model.eval() + torch.no_grad()
✅ 计算指标、可视化、日志记录时使用
✅ 推理部署时使用
✅ 需要临时阻断梯度传播时使用

❌ 训练前向传播时不要使用（无法反向传播）
❌ 需要梯度检查点 (gradient checkpointing) 时不要使用

# 数学和统计
- torch.mean()
- torch.std()
- torch.var()
- torch.exp()
- torch.log()
- torch.sin()
- torch.cos()

# 张量变换和操作
- torch.split 用于将张量沿指定维度分割成多个子张量
- torch.chunk 按张量分割成特定数量的块
- torch.sort 对张量进行排序
- torch.topk 返回张量中最大的k个元素

## torch.split 用于将张量沿指定维度分割成多个子张量

In [ ]:
torch.split(tensor, split_size_or_sections, dim=0)

| 参数                       | 说明                |
| ------------------------ | ----------------- |
| `tensor`                 | 要分割的输入张量          |
| `split_size_or_sections` | 分割大小（整数）或每个块的大小列表 |
| `dim`                    | 沿哪个维度分割，默认为 0     |


### 按固定大小分割


In [11]:
import torch

x = torch.arange(10).reshape(5,2)
print(x)

# 沿着dim=0分割，每块大小为2
splits = torch.split(x,2)
print(splits)
for i,s in enumerate(splits):
    print(f"Split {i}:{s}\n")
    
# 按指定大小列表分割
splits_by_list = torch.split(x,[1,3,1])
print(splits_by_list)
for i ,s in enumerate(splits_by_list):
    print(f"splits_by_list{i}:shape{s.shape}")
    
# 沿着不同维度分割
x = torch.randn(4,6)
# 沿着列 dim=1分割，每块2列
splits_by_col = torch.split(x,2,dim=1)
print([(s,s.shape) for s in splits_by_col])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
(tensor([[0, 1],
        [2, 3]]), tensor([[4, 5],
        [6, 7]]), tensor([[8, 9]]))
Split 0:tensor([[0, 1],
        [2, 3]])

Split 1:tensor([[4, 5],
        [6, 7]])

Split 2:tensor([[8, 9]])

(tensor([[0, 1]]), tensor([[2, 3],
        [4, 5],
        [6, 7]]), tensor([[8, 9]]))
splits_by_list0:shapetorch.Size([1, 2])
splits_by_list1:shapetorch.Size([3, 2])
splits_by_list2:shapetorch.Size([1, 2])
[(tensor([[-0.0568, -1.1476],
        [ 2.8055, -0.1285],
        [-1.2258, -0.6135],
        [-0.9480,  0.5295]]), torch.Size([4, 2])), (tensor([[-0.1591, -0.2219],
        [-1.1372,  1.6473],
        [ 0.6121, -1.1295],
        [-0.4495, -0.1827]]), torch.Size([4, 2])), (tensor([[-1.2237, -1.6293],
        [ 0.5516, -1.8563],
        [ 0.2736, -1.4244],
        [ 0.3505, -0.7930]]), torch.Size([4, 2]))]


| 特性    | `torch.split` | `torch.chunk` |
| ----- | ------------- | ------------- |
| 控制方式  | 指定每块大小        | 指定块的数量        |
| 不均匀分割 | ✅ 支持          | ❌ 尽量均匀        |
| 灵活性   | 更高            | 较简单           |


In [13]:
x = torch.arange(10)

# split: 指定每块大小为 3
splits = torch.split(x, 3)  # -> (3,), (3,), (3,), (1,)

# chunk: 指定分成 3 块
chunks = torch.chunk(x, 3)  # -> (4,), (3,), (3,)
print(splits)
print(chunks)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([9]))
(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([8, 9]))


### 常见应用场景
- 批处理分割：将大批量数据分成小批次
- 模型并行：将网络层输出分割到不同设备
- 序列处理：将长序列分割成固定长度的片段
- 多头注意力：分割 Q/K/V 矩阵到多个注意力头

In [19]:
# 多头注意力示例
batch,seq_len,d_model = 2,10,512
num_heads = 8

x = torch.randn(batch,seq_len,d_model)
# 分割到8个头，每个头64维
heads = torch.split(x,d_model // num_heads,dim=-1)
# 返回的是元组（tuple），不是列表


## torch.sort 张量排序

In [ ]:
torch.sort(input, dim=-1, descending=False, stable=False)

| 参数           | 说明                       |
| ------------ | ------------------------ |
| `input`      | 输入张量                     |
| `dim`        | 沿哪个维度排序，默认最后一维           |
| `descending` | `True` 降序，`False` 升序（默认） |
| `stable`     | `True` 保持相等元素的原始顺序       |


In [21]:
import torch
x = torch.tensor([3, 1, 4, 1, 5, 9, 2, 6])
# 升序排序（默认）
sorted_vals,sorted_indices = torch.sort(x)
print(sorted_vals)
print(sorted_indices)
# 降序排序
sorted_vals,_ = torch.sort(x,descending=True)
print(sorted_vals)

tensor([1, 1, 2, 3, 4, 5, 6, 9])
tensor([1, 3, 6, 0, 2, 4, 7, 5])
tensor([9, 6, 5, 4, 3, 2, 1, 1])


### 多维张量排序


In [24]:
# 2D 张量，沿不同维度排序
x = torch.tensor([[3, 1, 4], 
                  [1, 2, 9]])

# dim=1 行内排序
vals,indices = torch.sort(x,dim=1)
print(vals)
# dim=0 列间排序
vals,indices = torch.sort(x,dim=0)
print(vals)

tensor([[1, 3, 4],
        [1, 2, 9]])
tensor([[1, 1, 4],
        [3, 2, 9]])


In [27]:
x = torch.randn(100)
print(x)
top5_vals,top5_indices = torch.topk(x,k=5)
print(top5_vals)

#等价但效率低
sorted_vals,sorted_indices = torch.sort(x,descending=True)
top5_vals_slow = sorted_vals[:5]

tensor([ 1.8057e-01, -1.1195e+00, -2.9744e-01, -7.9518e-01, -3.3265e-01,
         5.8419e-01,  1.5053e-04, -1.5549e-01, -3.8602e-01,  3.4424e-01,
        -2.6174e-02, -9.6053e-01,  6.4436e-01, -6.2751e-01,  4.2535e-01,
         1.0770e+00,  6.1110e-01,  4.0163e-01, -4.0674e-01, -1.2346e+00,
         6.7546e-01,  1.2928e+00,  9.6945e-01,  1.1082e+00, -1.3537e+00,
         9.2555e-01,  1.3541e+00,  1.0616e+00, -7.5932e-01, -7.2701e-01,
        -2.4911e-01,  4.1319e-01, -1.4326e-01,  6.1045e-01,  1.2641e+00,
         3.9316e-01, -1.1425e+00, -2.1912e-01,  2.2871e+00,  2.6443e-02,
         1.1836e+00, -3.9725e-01, -6.5448e-01,  4.1409e-01, -1.4582e-01,
         1.0150e+00, -2.8177e-01,  1.2790e-01, -2.1058e-01, -1.2063e+00,
         4.1072e-01, -4.9600e-01,  1.0076e+00, -1.7793e-02, -6.6008e-01,
         5.6450e-01,  4.1826e-01, -2.4700e-01, -1.4148e+00, -1.3666e+00,
        -7.5316e-01,  2.5952e-01,  3.7112e-02, -2.9710e-01, -8.4856e-01,
        -9.8241e-01,  1.2585e+00, -8.6314e-01, -2.0

### 实际应用场景

In [1]:
import torch
# 排序后去中位数（奇数长度）
x = torch.randn(101)
median = torch.sort(x).values[50]

# 获取排序索引用于重排其他张量
scores = torch.randn(10)
_,rank = torch.sort(scores,descending=True)
print(rank[0])

# 序列模型中的排序
batch_seq = torch.randn(32,100,64) # (batch,seq,dim)
print(batch_seq[0])
print(batch_seq.shape)

sorted_seq,_ = torch.sort(batch_seq,dim=1) # 沿序列维度排序
print(sorted_seq)

tensor(9)
tensor([[ 0.2444, -0.6826,  0.0648,  ...,  0.5164,  1.0901,  0.1706],
        [ 0.0403, -0.0572,  0.0985,  ..., -0.4805,  0.2692, -0.2115],
        [-1.1448, -1.3726, -1.4271,  ...,  1.1465,  0.3592, -0.3959],
        ...,
        [ 0.0749,  1.1477,  1.7434,  ..., -0.4971,  0.3074, -0.7891],
        [ 0.0756,  2.5400,  1.1912,  ...,  1.2287,  0.9084, -0.7732],
        [-1.0030,  0.1073,  1.2851,  ..., -0.4750,  0.2657,  0.9514]])
torch.Size([32, 100, 64])
tensor([[[-2.4106, -2.5571, -1.8603,  ..., -2.1906, -2.9272, -2.1202],
         [-2.2267, -2.0840, -1.8013,  ..., -2.0206, -2.4382, -1.8810],
         [-2.0038, -1.9635, -1.7093,  ..., -1.6463, -2.3020, -1.7362],
         ...,
         [ 2.2054,  2.0113,  1.7032,  ...,  1.8520,  1.5951,  1.8055],
         [ 2.2256,  2.1479,  1.7434,  ...,  1.9155,  1.6205,  1.9417],
         [ 2.8017,  2.5400,  2.0025,  ...,  3.1184,  2.0670,  2.2052]],

        [[-3.0344, -1.9501, -2.6802,  ..., -2.7579, -2.7987, -2.1570],
         [-2.1702

| 函数              | 返回值                 | 用途         |
| --------------- | ------------------- | ---------- |
| `torch.sort`    | `(values, indices)` | 需要排序后的值    |
| `torch.argsort` | 仅 `indices`         | 只需要索引，节省内存 |


|    维度   |  大小 | 含义                                        |
| :-----: | :-: | :---------------------------------------- |
| `dim=0` |  32 | **batch size**（批次大小）— 32个独立样本             |
| `dim=1` | 100 | **sequence length**（序列长度）— 每个样本100个时间步/位置 |
| `dim=2` |  64 | **feature dim**（特征维度）— 每个位置64维向量          |


In [2]:
import torch

x = torch.tensor([3,1,4])

# 等价操作
_,indices = torch.sort(x)
indices1 = torch.argsort(x)

torch.equal(indices,indices1)

True