In [3]:
import torch
log_prob = torch.tensor([[ -2.0,  -1.5,  -3.0],   # 样本 0
                         [ -4.0,  -1.0,  -5.0],   # 样本 1
                         [ -2.5,  -2.0,  -1.2]])
print(log_prob.shape)

safe_target = torch.tensor([1,0,2])

torch.Size([3, 3])


In [5]:
# 方法A ：使用高级索引
idx = torch.arange(log_prob.size(0))
print(idx)
A = log_prob[idx,safe_target]

# 方法B：gather
B_with_unsqueeze = log_prob.gather(dim=1,index=safe_target.unsqueeze(1))
print(B_with_unsqueeze.shape)
print(B_with_unsqueeze)
B_with_squeeze = B_with_unsqueeze.squeeze(1)
print(B_with_squeeze.shape)
print(B_with_squeeze)
print(torch.equal(A,B_with_squeeze))

tensor([0, 1, 2])
torch.Size([3, 1])
tensor([[-1.5000],
        [-4.0000],
        [-1.2000]])
torch.Size([3])
tensor([-1.5000, -4.0000, -1.2000])
True


## dim=1 告诉 gather：“按列方向（即第 1 维）去取元素”。

### dim=k  ⇒  在“第 k 维”上把索引号当成下标去抽元素，其他维度保持不变。

In [9]:
src = torch.tensor([[ 10,  20,  30],   # 0 行
                    [ 40,  50,  60],   # 1 行
                    [ 70,  80,  90]])  # 2 行
print(src.shape)

index = torch.tensor([[0],             # 取第 0 列
                      [2],             # 取第 2 列
                      [1]])            # 取第 1 列
print(index.shape)

# dim=1 ⇒ 在列方向（axis=1）用 index 的值当下标
out = src.gather(dim=1, index=index)
# 结果形状与 index 完全一致：[3, 1]
print(out.shape)
print(out)


torch.Size([3, 3])
torch.Size([3, 1])
torch.Size([3, 1])
tensor([[10],
        [60],
        [80]])


In [8]:
index_row = torch.tensor([[0, 1, 2],
                          [0, 1, 2],
                          [0, 1, 2]])            # 形状 [3, 3]
src.gather(dim=0, index=index_row)              # 按行方向取
# 此时结果形状仍是 [3, 3]，但元素来自不同行、相同列。

tensor([[10, 50, 90],
        [10, 50, 90],
        [10, 50, 90]])

### “dim=几，就在第几维用索引号去抽，其余维度按坐标原样对应。”