## torch.clamp 是 PyTorch 的数值截断函数：
- 把张量元素全部限制到 [min, max] 区间，超出部分直接改成边界值。


torch.clamp(input, min=None, max=None, *, out=None) → Tensor

- 只给 min：大于 min 保留，小于 min 提至 min
- 只给 max：小于 max 保留，大于 max 降至 max
- 同时给：双向截断

In [3]:
import torch
x = torch.tensor([-1.0, 0.5, 2.5, 4.0])
torch.clamp(x, min=0, max=2)      

tensor([0.0000, 0.5000, 2.0000, 2.0000])

In [4]:
torch.clamp(x, min=0.3)     

tensor([0.3000, 0.5000, 2.5000, 4.0000])

In [5]:
torch.clamp(x, max=1) 

tensor([-1.0000,  0.5000,  1.0000,  1.0000])