- 与 torch.repeat 不同，repeat_interleave 是在单个维度上对每个元素分别重复指定次数，而不是整体复制整个张量。

In [ ]:
torch.repeat_interleave(input, repeats, dim=None, *, output_size=None)

In [1]:
import torch

x = torch.tensor([1,2,3])
y = torch.repeat_interleave(x,repeats=2)
print(y)

tensor([1, 1, 2, 2, 3, 3])


In [2]:
# 不同元素重复不同次数
x = torch.tensor([1,2,3])
repeats = torch.tensor([1,2,3])
y = torch.repeat_interleave(x,repeats)
print(y)

tensor([1, 2, 2, 3, 3, 3])


In [3]:
import torch
# 在指定维度上重复
x = torch.tensor([
    [1,2],
    [3,4]
])

# 在dim=0 （行方向上） 重复
y = torch.repeat_interleave(x,repeats=2,dim=0)
print(y)

# 在dim=1（列方向上）重复
z = torch.repeat_interleave(x,repeats=2,dim=1)
print(z)

tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])
tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])


In [4]:
# 使用张量指定每行/每列的重复次数

x = torch.tensor([
    [1,2],
    [3,4]
])
# 每一行重复不同次数 dim=0
repeats = torch.tensor([1,3])
y = torch.repeat_interleave(x,repeats,dim=0)
print(y)

tensor([[1, 2],
        [3, 4],
        [3, 4],
        [3, 4]])


## 与 torch.repeat() 的区别：
- repeat 是复制整个张量多次（类似 NumPy 的 tile）。
- repeat_interleave 是对每个元素进行重复（类似 NumPy 的 repeat）

In [ ]:
x = torch.tensor([1, 2])
print(x.repeat(2))               # → [1, 2, 1, 2]
print(torch.repeat_interleave(x, 2))  # → [1, 1, 2, 2]